// CONFIG VALIDATION ERR CONSTANTS
exports.CONFIG_VALIDATION_CODE = 'TC_CONFIG_VALIDATION_FAILED';
exports.CONFIG_VALIDATION_MESSAGE = 'Missing or Invalid ThrottleCore configuration';

// REDIS CONNECTION ERR CONSTANTS
exports.REDIS_CONN_FAILURE_CODE = 'TC_REDIS_CONN_ERR';
exports.REDIS_COMMAND_FAILURE_CODE = 'TC_REDIS_COMMAND_ERR';
exports.REDIS_CONN_FAILURE_MESSAGE = 'Failed to connect to Redis server'

// RATE LIMIT EXCEEDED
exports.RATE_LIMIT_EXCEEDED_CODE = 'TC_RATE_LIMIT_EXCEEDED';
exports.RATE_LIMIT_EXCEEDED_MESSAGE = 'Too many requests, please try again later'

// DUPLICATE REQUEST
exports.DUPLICATE_REQUEST_CODE = 'TC_DUPLICATE_REQUEST';
exports.DUPLICATE_REQUEST_MESSAGE = 'Duplicate request detected';